server:
  port: 8081
  ssl:
    enabled: false
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-alias: tomcat
    key-password: password

security:
  require-ssl: false
spring:
  datasource:
    driverClassName: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/connect-db?autoreconnect=true"
    username: "root"
    password: "root"
  application:
    name: "Connect-Service"
custom-property: "custom-value1"